name: build

on:
  workflow_dispatch:
    push:
      branches:
        - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y libsdl2-dev
            sudo apt-get install -y libsdl2-ttf-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install SDL2
            brew install SDL2_ttf
          else
            echo "$RUNNER_OS not supported"
          fi
        shell: bash

      # - name: Set PKG_CONFIG_PATH
      #   run: export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu:$PKG_CONFIG_PATH"

      # - name: Setup SDL2
      #   run: sudo cp -R ./_lib/* /usr/lib/pkgconfig

      - name: Build
        run: |
          chmod +x pack.sh
          ./pack.sh
        shell: bash



